name: Publish Core Resources

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.RMG_BUILD_AND_RELEASE }}
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - run: npm run postinstall

      - name: Pre-publish
        run: |
          chmod +x ./scripts/prepublish.sh
          ./scripts/prepublish.sh
        id: prepublish

      - name: Pulish to npm
        run: |
          cd ./package/dist
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.RMG_NPM_PUBLISH }}

      - name: Trigger RMG Templates rebuild
        run: |
          curl -XPOST -u "wongchito:${{ secrets.RMG_BUILD_AND_RELEASE }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/railmapgen/rmg-templates/actions/workflows/build.yml/dispatches \
          --data '{"ref": "main", "inputs": {"auto_deploy": "PRD"}}'
